setwd("C:/Users/mza0052/Desktop/Coursera/Exp_Ana")
hpctable <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
hpctable$Date <- as.Date(hpctable$Date, "%d/%m/%Y")
hpctable  <- hpctable [complete.cases(hpctable ),]
hpctable <- subset(hpctable,Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
plot(data=hpctable, Sub_metering_1~Date, type="l", ylab="Global Active Power (kilowatts)", xlab="")
lines(data=hpctable,Sub_metering_2~hpctable$Date,col='Red')
lines(data=hpctable,Sub_metering_3~hpctable$Date,col='Blue')
legend("topright", col=c("black", "red", "blue"), lwd=c(1,1,1), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()
