setwd("C:/Users/mza0052/Desktop/Coursera/Exp_Ana")
hpctable <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
hpctable$Date <- as.Date(hpctable$Date, "%d/%m/%Y")
hpctable  <- hpctable [complete.cases(hpctable ),]
hpctable <- subset(hpctable,Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
hpctable$Date<- paste(hpctable$Date, hpctable$Time)
hpctable$Date <- as.POSIXct(hpctable$Date)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(data=hpctable, Global_active_power~Date, type="l", ylab="Global Active Power (kilowatts)", xlab="")
plot(data=hpctable, Voltage~Date, type="l",ylab="Voltage (volt)", xlab="")
plot(data=hpctable, Sub_metering_1~Date, type="l", ylab="Global Active Power (kilowatts)", xlab="")
lines(data=hpctable, Sub_metering_2~Date,col='Red')
lines(data=hpctable, Sub_metering_3~Date,col='Blue')
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data=hpctable, Global_reactive_power~Date, type="l",ylab="Global Rective Power (kilowatts)",xlab="")
dev.copy(png,"plot4.png", width=480, height=480)
dev.off()
